/* ─── Segal Build — Core Categories Part 2 (remaining 10) ─── */
import { cat, type WorkCategory } from './types';

export const CORE_CATEGORIES_PART2: WorkCategory[] = [
  cat('plumbing', '🔧 Plumbing & Drainage', 'plumbing', 'trades',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Rough-in', 'Hot water', 'Drainage', 'Gas fitting'] }],
    [{ name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 1800, unit: 'allow', duration: 2, description: 'Rough-in pipework' },
     { name: 'Fit-off', trade: 'Plumbing', rate: 800, unit: 'allow', duration: 1, description: 'Connect fixtures' }],
    [{ description: 'Hot Water System', allowance: 2500, unit: 'item' }],
    ['All labour and materials', 'Compliance certification'],
    ['Appliance supply', 'Roofing works for flue'],
    [{ categoryId: 'waterproofing', type: 'suggested' }]),

  cat('waterproofing', '💧 Waterproofing', 'waterproofing', 'trades',
    [{ id: 'area', label: 'Area', type: 'select', options: ['Bathroom', 'Laundry', 'Balcony', 'Basement'] }],
    [{ name: 'Membrane Application', trade: 'Waterproofing', rate: 55, unit: 'area', duration: 1, description: 'AS3740 compliant membrane' }],
    [], ['AS3740 compliance', 'Membrane supply and application', 'Flood test and certification'],
    ['Structural repairs', 'Tiling over membrane'],
    [], 10, 'renovation'),

  cat('hvac', '❄️ HVAC', 'hvac', 'trades',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Split system', 'Ducted', 'Evaporative', 'Hydronic'] }],
    [{ name: 'Installation', trade: 'HVAC', rate: 2800, unit: 'item', duration: 1, description: 'Supply and install system' }],
    [{ description: 'A/C Unit', allowance: 3000, unit: 'item' }],
    ['Installation and commissioning', 'Electrical connection'],
    ['Structural penetrations', 'Building permit for external unit'],
    [{ categoryId: 'electrical', type: 'auto' }]),

  cat('roofing', '🏠 Roofing — Re-Roof', 'roofing', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Colorbond', 'Tiles', 'Zinc'] }],
    [{ name: 'Remove Old Roof', trade: 'Roofing', rate: 35, unit: 'area', duration: 2, description: 'Remove existing roofing' },
     { name: 'Install New Roof', trade: 'Roofing', rate: 120, unit: 'area', duration: 3, description: 'Supply and install new' }],
    [{ description: 'Roofing Material', allowance: 65, unit: '$/m²' }],
    ['Removal and disposal', 'New roofing installation', 'Flashings and ridges'],
    ['Structural repairs', 'Guttering', 'Insulation'],
    [{ categoryId: 'guttersFascia', type: 'auto' }, { categoryId: 'insulation', type: 'suggested' }]),

  cat('fencing', '🏗️ Fencing & Gates', 'fencing', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Timber paling', 'Colorbond', 'Aluminium', 'Pool fence'] }],
    [{ name: 'Post Holes & Posts', trade: 'Carpentry', rate: 45, unit: 'linear', duration: 1, description: 'Dig and set posts' },
     { name: 'Fence Construction', trade: 'Carpentry', rate: 120, unit: 'linear', duration: 2, description: 'Build fence' }],
    [], ['All materials and labour', 'Post holes and concrete'],
    ['Removal of old fence', 'Council permits', 'Pool compliance certification'],
    []),

  cat('concreting', '🧱 Concreting', 'concreting', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Slab', 'Footings', 'Paths', 'Driveway'] }],
    [{ name: 'Excavation & Prep', trade: 'Concreting', rate: 45, unit: 'area', duration: 1, description: 'Excavate and prepare base' },
     { name: 'Form & Pour', trade: 'Concreting', rate: 110, unit: 'area', duration: 2, description: 'Formwork and concrete pour' }],
    [], ['Excavation and prep', 'Concrete supply and pour', 'Basic finish'],
    ['Reinforcement', 'Exposed aggregate finish', 'Pump hire'],
    []),

  cat('pergola', '🏠 Pergola & Patio', 'pergola', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Timber pergola', 'Steel patio', 'Insulated roof'] }],
    [{ name: 'Posts & Frame', trade: 'Carpentry', rate: 350, unit: 'area', duration: 2, description: 'Construct frame' },
     { name: 'Roofing', trade: 'Roofing', rate: 120, unit: 'area', duration: 2, description: 'Install roofing' }],
    [], ['Complete structure', 'All materials'],
    ['Council permits', 'Electrical', 'Flooring/paving'],
    [{ categoryId: 'electrical', type: 'suggested' }, { categoryId: 'paving', type: 'suggested' }]),

  cat('landscaping', '🌿 Landscaping', 'landscaping', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Garden beds', 'Turf', 'Full landscape', 'Irrigation'] }],
    [{ name: 'Site Prep', trade: 'Landscaping', rate: 25, unit: 'area', duration: 1, description: 'Clear and prepare' },
     { name: 'Landscaping', trade: 'Landscaping', rate: 85, unit: 'area', duration: 3, description: 'Supply and install' }],
    [], ['All materials and labour', 'Basic planting'],
    ['Retaining walls', 'Irrigation systems', 'Lighting'],
    [{ categoryId: 'concreting', type: 'suggested' }]),

  cat('pools', '🏊 Pool & Spa', 'pools', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Concrete pool', 'Fiberglass', 'Renovation'] }],
    [{ name: 'Excavation & Steel', trade: 'Concreting', rate: 25000, unit: 'item', duration: 3, description: 'Excavate and steel fix' },
     { name: 'Shell Construction', trade: 'Concreting', rate: 30000, unit: 'item', duration: 3, description: 'Shotcrete/gunite shell' },
     { name: 'Tile & Coping', trade: 'Tiling', rate: 8000, unit: 'item', duration: 2, description: 'Waterline tile and coping' },
     { name: 'Equipment & Finish', trade: 'Plumbing', rate: 12000, unit: 'item', duration: 2, description: 'Pump, filter, interior finish' }],
    [{ description: 'Pool Equipment', allowance: 5000, unit: 'allowance' }],
    ['Pool shell construction', 'Equipment installation', 'Compliance fencing (separate)'],
    ['Pool fencing', 'Landscaping', 'Heating'],
    [{ categoryId: 'fencing', type: 'auto' }, { categoryId: 'electrical', type: 'auto' }, { categoryId: 'landscaping', type: 'suggested' }]),

  cat('windowsDoors', '🪟 Windows & Doors', 'windowsDoors', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Window replacement', 'New window', 'Door replacement', 'New door', 'Stacker/sliding'] }],
    [{ name: 'Remove Existing', trade: 'Carpentry', rate: 250, unit: 'item', duration: 0.5, description: 'Remove old window/door' },
     { name: 'Install New', trade: 'Carpentry', rate: 650, unit: 'item', duration: 1, description: 'Install new window/door' }],
    [{ description: 'Window/Door Unit', allowance: 1200, unit: 'item' }],
    ['Supply and install', 'Making good internal/external'],
    ['Structural alterations for new openings', 'Council permits', 'Flyscreens/security'],
    [{ categoryId: 'painting', type: 'suggested' }]),
];
