/* ─── Segal Build — Core Categories (20 key categories) ─── */
import { cat, catX, type WorkCategory } from './types';

export const CORE_CATEGORIES: WorkCategory[] = [
  catX('bathroom', '🚿 Bathroom / Wet Areas', 'bathroom', 'wet', 'assembly',
    [{ id: 'size', label: 'Approximate size', type: 'select', options: ['Small (3x2m)', 'Medium (4x3m)', 'Large (5x3m)', 'Custom'] },
     { id: 'type', label: 'Type', type: 'select', options: ['Full renovation', 'New ensuite', 'New bathroom'] },
     { id: 'tileExtent', label: 'Wall tile extent', type: 'select', options: ['Shower only + skirting tile', '1200mm high walls', '2100mm high walls', 'Floor-to-ceiling walls'] },
     { id: 'tileFinish', label: 'Tile finish level', type: 'select', options: ['Standard ceramic', 'Rectified porcelain', 'Feature wall included', 'Large-format premium'] },
     { id: 'vanityType', label: 'Vanity configuration', type: 'select', options: ['Standard 600mm vanity', '900mm vanity', '1200mm double vanity', 'Custom joinery vanity'] },
     { id: 'showerScreen', label: 'Shower screen', type: 'select', options: ['Semi-frameless', 'Frameless', 'Fully framed', 'Reuse existing', 'No shower screen'] },
     { id: 'fixtures', label: 'Fixture quality', type: 'select', options: ['Standard', 'Mid-range', 'Premium'] }],
    [{ name: 'Demolition & Removal', trade: 'Demo', rate: 2800, unit: 'item', duration: 2, description: 'Strip bathroom, remove debris' },
     { name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 3200, unit: 'allow', duration: 2, description: 'Rough-in new pipework' },
     { name: 'Waterproofing', trade: 'Waterproofing', rate: 185, unit: 'area', duration: 1, description: 'AS3740 compliant membrane' },
     { name: 'Wall Tiling', trade: 'Tiling', rate: 145, unit: 'area', duration: 3, description: 'Supply & install wall tiles' },
     { name: 'Floor Tiling', trade: 'Tiling', rate: 155, unit: 'area', duration: 2, description: 'Supply & install floor tiles' },
     { name: 'Electrical Fit-off', trade: 'Electrical', rate: 1200, unit: 'allow', duration: 1, description: 'Lights, exhaust, heated towel rail' },
     { name: 'Vanity & Mirror Install', trade: 'Carpentry', rate: 800, unit: 'item', duration: 1, description: 'Install vanity, mirror, accessories' },
     { name: 'Plumbing Fit-off', trade: 'Plumbing', rate: 2400, unit: 'allow', duration: 1, description: 'Tapware, shower, toilet install' },
     { name: 'Silicone & Finish', trade: 'Carpentry', rate: 350, unit: 'item', duration: 0.5, description: 'Seal all joints, final clean' }],
    [{ description: 'Tiles', allowance: 80, unit: '$/m²' }, { description: 'Tapware Set', allowance: 800, unit: 'set' }, { description: 'Vanity Unit', allowance: 1200, unit: 'item' }, { description: 'Toilet Suite', allowance: 600, unit: 'item' }, { description: 'Shower Screen', allowance: 900, unit: 'item' }, { description: 'Bath (if applicable)', allowance: 1100, unit: 'item' }],
    ['AS3740 waterproofing compliance', 'All labour and materials', 'Waste removal and disposal', 'Standard fixture installation', 'Silicone sealing to all joints'],
    ['Asbestos removal', 'Structural alterations', 'Council/permit fees', 'Engineer certification', 'Floor levelling if required'],
    [{ categoryId: 'cabinetry', type: 'suggested' }, { categoryId: 'flooring', type: 'suggested' }, { categoryId: 'painting', type: 'suggested' }],
    { dimensionMode: 'area', bundles: ['waterproofing', 'plumbing', 'tiling'], supportsPcItems: true, contingency: 10, workType: 'renovation' }),

  cat('kitchen', '🍳 Kitchen', 'kitchen', 'wet',
    [{ id: 'size', label: 'Kitchen size', type: 'select', options: ['Small (3x2m)', 'Medium (4x3m)', 'Large (5x4m)', 'Custom'] },
     { id: 'type', label: 'Scope', type: 'select', options: ['Full renovation', 'New kitchen', 'Cabinet replacement'] },
     { id: 'benchtop', label: 'Benchtop', type: 'select', options: ['Laminate', 'Stone (Caesarstone)', 'Porcelain'] }],
    [{ name: 'Demolition & Remove', trade: 'Demo', rate: 2200, unit: 'item', duration: 2, description: 'Strip existing kitchen' },
     { name: 'Plumbing/Electrical Rough-in', trade: 'Plumbing', rate: 2800, unit: 'allow', duration: 2, description: 'Relocate services' },
     { name: 'Plastering & Making Good', trade: 'Plastering', rate: 165, unit: 'area', duration: 2, description: 'Patch walls and ceilings' },
     { name: 'Cabinet Installation', trade: 'Carpentry', rate: 6500, unit: 'allow', duration: 3, description: 'Supply & install cabinetry' },
     { name: 'Benchtop Template & Install', trade: 'Carpentry', rate: 3500, unit: 'allow', duration: 2, description: 'Stone benchtop templating & install' },
     { name: 'Splashback Tiling', trade: 'Tiling', rate: 145, unit: 'area', duration: 1, description: 'Install splashback tiles' },
     { name: 'Plumbing/Electrical Fit-off', trade: 'Electrical', rate: 2200, unit: 'allow', duration: 1, description: 'Connect appliances, lighting' },
     { name: 'Painting', trade: 'Painting', rate: 65, unit: 'area', duration: 2, description: 'Paint walls and ceilings' }],
    [{ description: 'Kitchen Cabinets', allowance: 8000, unit: 'allowance' }, { description: 'Stone Benchtop', allowance: 4000, unit: 'allowance' }, { description: 'Sink & Tapware', allowance: 900, unit: 'set' }, { description: 'Handles & Hardware', allowance: 300, unit: 'allowance' }],
    ['Delivery & installation of cabinetry', 'Standard appliance connections', 'Splashback tiling', 'Making good walls and painting'],
    ['Appliance supply (unless PC)', 'Gas fitting if required', 'Structural alterations', 'Flooring replacement', 'Council/permit fees'],
    [{ categoryId: 'plumbing', type: 'auto' }, { categoryId: 'electrical', type: 'auto' }, { categoryId: 'painting', type: 'suggested' }, { categoryId: 'flooring', type: 'suggested' }]),

  cat('laundry', '🧺 Laundry', 'laundry', 'wet',
    [{ id: 'size', label: 'Laundry size', type: 'select', options: ['Small (2x2m)', 'Medium (3x2m)', 'Large (3x3m)'] },
     { id: 'type', label: 'Scope', type: 'select', options: ['Full renovation', 'New laundry', 'Upgrade'] }],
    [{ name: 'Demolition', trade: 'Demo', rate: 1200, unit: 'item', duration: 1, description: 'Remove existing laundry' },
     { name: 'Plumbing Rough-in', trade: 'Plumbing', rate: 1800, unit: 'allow', duration: 1, description: 'Rough-in new services' },
     { name: 'Waterproofing', trade: 'Waterproofing', rate: 185, unit: 'area', duration: 1, description: 'Membrane to floor' },
     { name: 'Floor & Wall Tiling', trade: 'Tiling', rate: 155, unit: 'area', duration: 2, description: 'Supply & install tiles' },
     { name: 'Cabinetry Install', trade: 'Carpentry', rate: 2500, unit: 'allow', duration: 1, description: 'Install laundry cabinets' },
     { name: 'Plumbing Fit-off', trade: 'Plumbing', rate: 1200, unit: 'allow', duration: 0.5, description: 'Connect tub, taps, trough' }],
    [{ description: 'Tub & Tapware', allowance: 500, unit: 'set' }, { description: 'Cabinetry', allowance: 2000, unit: 'allowance' }, { description: 'Tiles', allowance: 70, unit: '$/m²' }],
    ['AS3740 waterproofing', 'Cabinetry supply & install', 'Plumbing connections'],
    ['Appliance supply', 'Structural work', 'Floor levelling'],
    [{ categoryId: 'waterproofing', type: 'auto' }, { categoryId: 'plumbing', type: 'auto' }, { categoryId: 'cabinetry', type: 'suggested' }]),

  cat('flooring', '🪵 Flooring', 'flooring', 'wet',
    [{ id: 'type', label: 'Floor type', type: 'select', options: ['Timber', 'Tiles', 'Carpet', 'Vinyl', 'Polished Concrete'] },
     { id: 'area', label: 'Area', type: 'select', options: ['Single room', 'Multiple rooms', 'Whole house'] }],
    [{ name: 'Subfloor Preparation', trade: 'Carpentry', rate: 55, unit: 'area', duration: 1, description: 'Level and prepare subfloor' },
     { name: 'Floor Installation', trade: 'Flooring', rate: 85, unit: 'area', duration: 3, description: 'Supply & install flooring' },
     { name: 'Skirting & Trim', trade: 'Carpentry', rate: 25, unit: 'linear', duration: 1, description: 'Install skirting boards' }],
    [{ description: 'Flooring Material', allowance: 90, unit: '$/m²' }],
    ['Subfloor preparation', 'Quality flooring installation', 'Skirting and trim'],
    ['Furniture moving', 'Subfloor levelling compound', 'Door trimming'],
    [{ categoryId: 'painting', type: 'suggested' }]),

  cat('painting', '🎨 Painting', 'painting', 'trades',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Interior', 'Exterior', 'Both'] },
     { id: 'prep', label: 'Preparation', type: 'select', options: ['Minimal prep', 'Standard prep', 'Full prep & patching'] }],
    [{ name: 'Preparation', trade: 'Painting', rate: 12, unit: 'area', duration: 1, description: 'Sand, fill, prime' },
     { name: 'First Coat', trade: 'Painting', rate: 18, unit: 'area', duration: 1, description: 'Apply first coat' },
     { name: 'Second Coat', trade: 'Painting', rate: 18, unit: 'area', duration: 1, description: 'Apply second coat' }],
    [{ description: 'Paint Supply', allowance: 35, unit: '$/L' }],
    ['All preparation', 'Two-coat finish', 'Clean up and disposal'],
    ['Colour consulting', 'Wallpaper removal', 'Extensive patching', 'Lead paint management'],
    []),

  cat('demolition', '🏗️ Demolition', 'demolition', 'trades',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Internal strip', 'Partial demolition', 'Full demolition'] }],
    [{ name: 'Demolition', trade: 'Demo', rate: 150, unit: 'area', duration: 2, description: 'Demolish and remove' },
     { name: 'Skip Bin', trade: 'Demo', rate: 850, unit: 'item', duration: 0, description: 'Waste removal' }],
    [], ['Demolition and debris removal', 'Skip bin hire'], ['Asbestos removal', 'Structural engineering', 'Council permits'],
    [{ categoryId: 'structural', type: 'suggested' }]),

  cat('structural', '🏗️ Structural', 'structural', 'structural',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Wall removal', 'Beam install', 'Opening creation'] }],
    [{ name: 'Engineering', trade: 'Structural', rate: 2500, unit: 'item', duration: 5, description: 'Engineer design & certification' },
     { name: 'Propping & Demo', trade: 'Demo', rate: 1800, unit: 'item', duration: 1, description: 'Prop and remove load-bearing' },
     { name: 'Beam Install', trade: 'Structural', rate: 4500, unit: 'item', duration: 2, description: 'Supply and install beam' }],
    [{ description: 'Steel Beam', allowance: 2500, unit: 'item' }],
    ['Engineering certification', 'All structural work'], ['Making good finishes', 'Relocating services'],
    [{ categoryId: 'demolition', type: 'auto' }], 15, 'structural'),

  cat('decking', '🪵 Decking', 'decking', 'external',
    [{ id: 'type', label: 'Type', type: 'select', options: ['Merbau', 'Composite', 'Spotted Gum', 'Treated Pine'] }],
    [{ name: 'Subframe', trade: 'Carpentry', rate: 85, unit: 'area', duration: 2, description: 'H4 treated subframe' },
     { name: 'Decking Install', trade: 'Carpentry', rate: 180, unit: 'area', duration: 3, description: 'Supply and install decking' },
     { name: 'Balustrade', trade: 'Carpentry', rate: 280, unit: 'linear', duration: 2, description: 'If required >1m height' }],
    [{ description: 'Decking Material', allowance: 120, unit: '$/m²' }],
    ['Quality subframe', 'Decking installation', 'Stainless steel fixings'],
    ['Stumps/foundations', 'Staining/oiling', 'Council permits for >1m'],
    [{ categoryId: 'fencing', type: 'suggested' }]),

  catX('electrical', '⚡ Electrical', 'electrical', 'trades', 'trade',
    [{ id: 'scope', label: 'Scope', type: 'select', options: ['New fit-out', 'Rewire', 'Upgrade switchboard', 'Add circuits'] }],
    [{ name: 'Electrical Rough-in', trade: 'Electrical', rate: 85, unit: 'area', duration: 2, description: 'Rough-in cabling' },
     { name: 'Fit-off', trade: 'Electrical', rate: 800, unit: 'item', duration: 1, description: 'Install fittings and test' }],
    [], ['All cabling and installation', 'Compliance certificate (CES)', 'AS/NZS 3000 compliance'],
    ['Light fitting supply', 'Data cabling', 'Solar/battery'],
    [{ categoryId: 'smartHome', type: 'suggested' }],
    { usesParametric: true, supportsPcItems: false }),
];

// Import remaining core categories from split files (300-line rule)
import { CORE_CATEGORIES_PART2 } from './corePart2';
import { CORE_CATEGORIES_PART3, CORE_CATEGORIES_BUILDS } from './corePart3';

// Re-export combined array
CORE_CATEGORIES.push(...CORE_CATEGORIES_PART2, ...CORE_CATEGORIES_PART3, ...CORE_CATEGORIES_BUILDS);
